# THIS FILE IS AUTOMATICALLY GENERATED
# Project: C:\Design01\Design01.cydsn\Design01.cyprj
# Date: Sun, 16 Nov 2014 19:43:51 GMT
#set_units -time ns
create_clock -name {CyHFCLK} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/hfclk}]]
create_clock -name {CyIMO} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/imo}]]
create_clock -name {CySYSCLK} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/sysclk}]]
create_clock -name {CyILO} -period 31250 -waveform {0 15625} [list [get_pins {ClockBlock/ilo}]]
create_clock -name {CyLFCLK} -period 31250 -waveform {0 15625} [list [get_pins {ClockBlock/lfclk}]]


# Component constraints for C:\Design01\Design01.cydsn\TopDesign\TopDesign.cysch
# Project: C:\Design01\Design01.cydsn\Design01.cyprj
# Date: Sun, 16 Nov 2014 19:43:48 GMT
